#!/bin/bash
coan source --filter c,h --recurse ../c/sqlite -K -E \
-DSQLITE_DQS=0 \
-DSQLITE_THREADSAFE=0 \
-DSQLITE_DEFAULT_MEMSTATUS=0 \
-DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 \
-DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
-DSQLITE_MAX_EXPR_DEPTH=0 \
-DSQLITE_OMIT_DECLTYPE \
-DSQLITE_OMIT_DEPRECATED \
-DSQLITE_OMIT_PROGRESS_CALLBACK \
-DSQLITE_OMIT_SHARED_CACHE \
-USQLITE_USE_ALLOCA \
-DSQLITE_OMIT_AUTOINIT \
-USQLITE_ENABLE_FTS3 \
-USQLITE_ENABLE_FTS3_PARENTHESIS \
-USQLITE_ENABLE_FTS3_TOKENIZER \
-USQLITE_ENABLE_FTS4
